name: Wiz Code Security Scan

on: [push, pull_request]

jobs:
  wiz-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # IaC Scanning (Terraform/CloudFormation/K8s)
      - name: Scan Infrastructure-as-Code
        uses: wiz-io/wiz-action@v1
        with:
          wiz-api-token: ${{ secrets.WIZ_API_TOKEN }}
          scan-type: iac
          directory: ./infra

      # Secrets Detection
      - name: Scan for Secrets
        uses: wiz-io/wiz-action@v1
        with:
          wiz-api-token: ${{ secrets.WIZ_API_TOKEN }}
          scan-type: secrets

      # Container Image Scanning
      - name: Scan Container Image
        uses: wiz-io/wiz-action@v1
        with:
          wiz-api-token: ${{ secrets.WIZ_API_TOKEN }}
          scan-type: container
          image: myapp:latest