apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"argoproj.io/v1alpha1","kind":"Rollout","metadata":{"annotations":{},"name":"curiosity-rollouts","namespace":"curiosity"},"spec":{"replicas":5,"revisionHistoryLimit":2,"selector":{"matchLabels":{"app":"curiosity"}},"strategy":{"canary":{"steps":[{"setWeight":20},{"pause":{}},{"setWeight":40},{"pause":{"duration":10}},{"setWeight":60},{"pause":{"duration":10}},{"setWeight":80},{"pause":{"duration":10}}]}},"template":{"metadata":{"labels":{"app":"rollouts-demo"}},"spec":{"containers":[{"image":"argoproj/rollouts-demo:blue","name":"rollouts-demo","ports":[{"containerPort":8080,"name":"http","protocol":"TCP"}],"resources":{"requests":{"cpu":"5m","memory":"32Mi"}}}]}}}}
    rollout.argoproj.io/revision: "1"
  creationTimestamp: "2025-04-10T13:05:59Z"
  generation: 2
  name: curiosity-rollouts
  namespace: curiosity
  resourceVersion: "137338026"
  uid: 852769dc-e22d-4976-9329-1b1aee681658
spec:
  replicas: 5
  restartAt: "2025-05-01T16:26:24Z"
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: curiosity
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {}
      - setWeight: 40
      - pause:
          duration: 10
      - setWeight: 60
      - pause:
          duration: 10
      - setWeight: 80
      - pause:
          duration: 10
  template:
    metadata:
      labels:
        app: curiosity
    spec:
      containers:
      - image: argoproj/rollouts-demo:blue
        name: curiosity-rollouts
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 5m
            memory: 32Mi
status:
  HPAReplicas: 5
  availableReplicas: 5
  blueGreen: {}
  canary: {}
  conditions:
  - lastTransitionTime: "2025-04-10T13:05:59Z"
    lastUpdateTime: "2025-04-10T13:05:59Z"
    message: RolloutCompleted
    reason: RolloutCompleted
    status: "True"
    type: Completed
  - lastTransitionTime: "2025-05-06T13:29:47Z"
    lastUpdateTime: "2025-05-06T13:29:47Z"
    message: Rollout is healthy
    reason: RolloutHealthy
    status: "True"
    type: Healthy
  - lastTransitionTime: "2025-04-10T13:05:59Z"
    lastUpdateTime: "2025-05-06T13:29:47Z"
    message: ReplicaSet "rollouts-demo-687d76d795" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-05-06T13:29:47Z"
    lastUpdateTime: "2025-05-06T13:29:47Z"
    message: Rollout has minimum availability
    reason: AvailableReason
    status: "True"
    type: Available
  currentPodHash: 687d76d795
  currentStepHash: f64cdc9d
  currentStepIndex: 8
  observedGeneration: "2"
  phase: Healthy
  readyReplicas: 5
  replicas: 5
  restartedAt: "2025-05-01T16:26:24Z"
  selector: app=rollouts-demo
  stableRS: 687d76d795
  updatedReplicas: 5
