apiVersion: v1
kind: ConfigMap
metadata:
  name: strimzi-cluster-operator
  namespace: kafka  # Replace with the namespace where Strimzi is installed
data:
  # Example: metrics configuration for Prometheus JMX Exporter
  metrics-config.yml: |
    lowercaseOutputName: true
    rules:
      - pattern: kafka.server<type=(.+), name=(.+), clientId=(.+), topic=(.+), partition=(.*)><>Value
        name: kafka_server_$1_$2
        type: GAUGE
        labels:
          clientId: "$3"
          topic: "$4"
          partition: "$5"
      # Add more rules as needed